services:
  # --- O Banco de Dados ---
  db:
    image: postgres:15
    container_name: datagen-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datagen_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-gen-network

  # --- O Gerenciador (pgAdmin) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: datagen-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"                   # Acessar via navegador na porta 5050
    depends_on:
      - db
    networks:
      - data-gen-network

volumes:
  postgres_data:

networks:
  data-gen-network:
    driver: bridge
    name: data-gen-network